Repository RoastSoftware/roaster, pull requests merged in 2018-11, with the labels that each got.

#12 ci+cmd: add code coverage and badges in README.md (fixes #5)
  .gitignore
  .travis.yml
  README.md
  cmd/roasterd/main.go
  go.mod
  go.sum
Labels: Enhancement, On hold

#20 docs: add project description (fixes #19)
  README.md
Labels: Docs

#21 doc: add AWS architecture overview and wireframes
  .gitattributes
  doc/architecture/Architecture-M7011E.png
  doc/wireframes/Web 1920 – 1.png
  doc/wireframes/Web 1920 – 1@2x.png
  doc/wireframes/Web 1920 – 2.png
  doc/wireframes/Web 1920 – 2@2x.png
  doc/wireframes/Web 1920 – 3.png
  doc/wireframes/Web 1920 – 3@2x.png
  doc/wireframes/Web 1920 – 4.png
  doc/wireframes/Web 1920 – 4@2x.png
  doc/wireframes/roaster.xd
Labels: Docs

#24 ci: add automatic deploy to AWS using Travis CI
  .gitignore
  .travis.yml
  Procfile
Labels: Environment, Urgent

#23 www+controller+model+doc+session+tool: add file structure
  .gitignore
  controller/README.md
  controller/controller.go
  controller/controller_test.go
  doc/README.md
  middleware/README.md
  middleware/auth/auth.go
  middleware/auth/auth_test.go
  model/README.md
  model/forwardengineer/schema.go
  model/forwardengineer/schema.sql
  model/model.go
  model/model_test.go
  model/user.go
  model/user_test.go
  session/README.md
  session/session.go
  session/session_test.go
  tool/README.md
  www/README.md
  www/dist/.gitkeep
  www/index.html
  www/package-lock.json
  www/package.json
  www/src/components/Example.tsx
  www/src/index.tsx
  www/tsconfig.json
  www/webpack.config.js
Labels: Docs, Environment

#30 cmd+aws: read PORT env and use as port (fixes #29)
  Procfile
  cmd/roasterd/main.go
  controller/controller.go
Labels: Bug, Urgent

#31 ci: build front end in Travis CI (fixes: #27)
  .travis.yml
  www/package-lock.json
  www/package.json
  www/webpack.common.js
  www/webpack.dev.js
  www/webpack.prod.js
Labels: Enhancement, Environment

#33 docker: add Dockerfile based on alpine:edge (fixes: #32)
  .travis.yml
  Dockerfile
Labels: Enhancement, Environment

#34 doc: front end stack visualization
  doc/architecture/stack.png
Labels: Environment, Urgent

#37 ci+docker: change to new AWS EB environment
  .travis.yml
  Dockerfile
Labels: Bug, Environment

#39 aws: remove Procfile (fixes #38)
  Procfile
Labels: Bug

#41 De-bloated/removed React and replaced with the Mithril framework (fixes: #35)
  doc/architecture/stack.png
  www/README.md
  www/index.html
  www/package-lock.json
  www/package.json
  www/src/components/Example.tsx
  www/src/index.ts
  www/src/index.tsx
  www/src/models/Users.ts
  www/src/views/UserList.ts
  www/tsconfig.json
  www/webpack.common.js
Labels: Docs, Enhancement

#43 www: removed outdated comment (fixes: #42)
  www/webpack.common.js
Labels: Bug, Docs

#45 ci: added retry option on commands that download (fixes: #44)
  .travis.yml
Labels: Enhancement, Environment

#50 Create PULL_REQUEST_TEMPLATE.md (fixes: #49)
  PULL_REQUEST_TEMPLATE.md
Labels: Docs, Enhancement

#47 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Docs

#46 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Docs

#48 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Docs

#51 rename: move github specific stuff into .github/
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs, Enhancement

#52 doc/restapi: preliminary REST API spec (fixes #40)
  doc/restapi/Roaster-REST-API.md
Labels: Docs

#54 www/src: added view skeletons (fixes: #53, #11, #9)
  www/src/index.ts
  www/src/views/UserList.ts
  www/src/views/about.ts
  www/src/views/header.ts
  www/src/views/home.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/statistics.ts
Labels: Enhancement, UI

#58 doc: add preliminary instructions for setting up dev-env (updates: #57)
  README.md
Labels: Docs

#66 www: add inital styling with Semantic UI (fixes: #63)
  www/index.html
  www/package-lock.json
  www/package.json
  www/src/views/about.ts
  www/src/views/base.ts
  www/src/views/header.ts
  www/src/views/home.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/statistics.ts
Labels: Frontend, UI

#67 doc/postgresql: add database w/ initial tables (fixes: #13)
  doc/postgresql/roaster-database-v0.0.1.png
  doc/postgresql/roaster-database-v0.0.1.sql
  doc/postgresql/roaster-database-v0.0.1.uml
Labels: DB, Design choice, Docs

#69 cmd+model: generate SQL queries for model and connect to psql (updates: #59)
  cmd/inlinesql/main.go
  controller/user/user.go
  go.mod
  go.sum
  model/forwardengineer/schema.go
  model/forwardengineer/schema.sql
  model/model.go
Labels: Backend

#73 www: implement Monaco IDE (fixes: #62, #68)
  www/package-lock.json
  www/package.json
  www/src/views/editor.ts
  www/src/views/home.ts
  www/tsconfig.json
  www/webpack.common.js
Labels: Enhancement, Frontend, UI

#75 www: lazy-load Monaco Editor, add new npm run build-small
  Dockerfile
  www/.babelrc
  www/.eslintrc.json
  www/package-lock.json
  www/package.json
  www/src/views/editor.ts
  www/src/views/nav.ts
  www/tsconfig.json
  www/tslint.json
  www/webpack.common.js
  www/webpack.dev.js
  www/webpack.prod.js
  www/webpack.quick.js
Labels: Bug, Enhancement, Environment, Frontend

#79 aws+ci: fix AWS timeout problem (fixes: #78)
  .ebignore
  .gitignore
  .travis.yml
  Dockerfile
Labels: Bug, Environment, ULTRA URGENT, Urgent

#81 www: added loader when waiting for lazyloaded editor (fixes: #80)
  www/.babelrc
  www/package-lock.json
  www/package.json
  www/src/views/editor.ts
Labels: Frontend, UI

#83 www+controller: move all assets into dist folders (fixes: #82)
  .travis.yml
  controller/controller.go
  www/dist/.gitkeep
  www/index.html
  www/package-lock.json
  www/package.json
  www/src/index.ts
  www/webpack.common.js
  www/webpack.prod.js
  www/webpack.quick.js
Labels: Backend, Enhancement, Environment, Frontend

#84 ci: fix dist in dist folder
  .travis.yml
Labels: ULTRA URGENT, Urgent

#71 routes+model: redirect middleware and user authenticaton API
  README.md
  cmd/roasterd/main.go
  cmd/testbcrypt/testbcrypt.go
  cmd/testbcrypt/testbcrypt_test.go
  controller/controller.go
  controller/session/session.go
  controller/static/static.go
  controller/user/user.go
  doc/postgresql/roaster-database-v0.0.1.png
  doc/postgresql/roaster-database-v0.0.1.uml
  doc/postgresql/roaster-database-v0.0.2.png
  doc/postgresql/roaster-database-v0.0.2.sql
  doc/postgresql/roaster-database-v0.0.2.uml
  go.mod
  go.sum
  middleware/auth/auth.go
  middleware/auth/auth_test.go
  middleware/contenttype.go
  middleware/csrf.go
  middleware/redirect.go
  model/forwardengineer/schema.go
  model/model.go
  model/user.go
  session/session.go
  util/util.go
  www/package-lock.json
Labels: Backend, Blocked, DB

#98 www/src/views: refactor home page with flexboxes and add example warning/error
  www/src/views/base.ts
  www/src/views/editor.ts
  www/src/views/home.ts
  www/src/views/nav.ts
  www/webpack.common.js
Labels: Enhancement, Frontend

#89 www/src: login page and basic user model
  .travis.yml
  www/.eslintignore
  www/.eslintrc.json
  www/package-lock.json
  www/package.json
  www/src/index.ts
  www/src/models/Users.ts
  www/src/models/user.ts
  www/src/views/about.ts
  www/src/views/base.ts
  www/src/views/editor.ts
  www/src/views/header.ts
  www/src/views/home.ts
  www/src/views/login.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/statistics.ts
  www/webpack.common.js
Labels: Frontend, UI

#102 correct api paths (fixes: #100)
  www/src/models/user.ts
  www/src/views/login.ts
Labels: Bug, Frontend

#101 www/src/views: add border to message column
  www/src/views/home.ts
Labels: Frontend, PANIC ATTACK, UI, ULTRA URGENT, Urgent, WHATEVERCOMESAFTERULTRAURGENT

#107 doc/architecture: security documentation (fixes: #106)
  doc/architecture/security.md
Labels: Docs, Enhancement
