Repository RoastSoftware/roaster, pull requests merged in 2018-12, with the labels that each got.

#104 www/src: network and authentication handling
  cmd/roasterd/main.go
  controller/controller.go
  controller/session/session.go
  controller/user/user.go
  go.mod
  middleware/csrf.go
  model/user.go
  session/session.go
  www/package-lock.json
  www/package.json
  www/src/assets/icons/roaster-icon-black.svg
  www/src/assets/icons/roaster-icon-teal.svg
  www/src/assets/icons/roaster-icon-white.svg
  www/src/index.ts
  www/src/models/apiError.ts
  www/src/models/user.ts
  www/src/services/auth.ts
  www/src/services/network.ts
  www/src/views/home.ts
  www/src/views/login.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/webpack.common.js
Labels: Backend, Frontend

#114 doc/restapi: update documentation for REST API since #104
  doc/restapi/Roaster-REST-API.md
Labels: Docs

#117 implement chart.js example graf (fixes: #109)
  doc/architecture/stack.png
  model/forwardengineer/schema.sql
  www/package-lock.json
  www/package.json
  www/src/models/statistics.ts
  www/src/views/statistics.ts
Labels: Frontend, UI

#118 doc/restapi: friend, feed and statistics endpoints API spec
  doc/restapi/Roaster-REST-API.md
Labels: Backend, Design choice, Docs

#122 avatar changeable, profile connected with API request (fixes: #111)(fixes: #120)
  controller/avatar/avatar.go
  controller/controller.go
  controller/user/user.go
  doc/postgresql/roaster-database-v0.0.2.sql
  go.mod
  go.sum
  model/avatar.go
  model/forwardengineer/schema.go
  model/forwardengineer/schema.sql
  www/.eslintrc.json
  www/src/models/user.ts
  www/src/services/auth.ts
  www/src/services/network.ts
  www/src/views/profile.ts
  www/src/views/register.ts
Labels: Backend, Frontend, UI

#124 purge the javascript (fixes: #103)
  www/package.json
  www/webpack.common.ts
  www/webpack.dev.ts
  www/webpack.prod.ts
Labels: Frontend, ULTRA URGENT

#119 Update README.md
  README.md
Labels: Docs, Enhancement

#133 doc+model+www: display roast result in frontend (fixes #128)
  doc/postgresql/roaster-database-v0.0.2.sql
  model/forwardengineer/schema.go
  model/roast.go
  www/src/models/editor.ts
  www/src/views/editor.ts
  www/src/views/home.ts
Labels: DB, Frontend

#138 controller/roast: allow unregistered users to get roasted (fixes: #136)
  controller/roast/roast.go
Labels: Backend, Bug

#132 www/src: about page and user page
  www/src/index.ts
  www/src/models/statistics.ts
  www/src/views/about.ts
  www/src/views/login.ts
  www/src/views/profile.ts
  www/src/views/user.ts
Labels: Frontend, UI

#140 refactor+router: move controller to router and better error handling
  cmd/roasterd/main.go
  controller/README.md
  controller/avatar/avatar.go
  controller/controller.go
  controller/controller_test.go
  controller/roast/roast.go
  controller/static/static.go
  go.mod
  go.sum
  router/README.md
  router/route/avatar.go
  router/route/handler.go
  router/route/roast.go
  router/route/session.go
  router/route/static.go
  router/route/user.go
  router/router.go
  router/router_test.go
Labels: Backend, Enhancement

#142 analyze+www: add example code w/ complexity problem and fix analyze test
  analyze/flake8_test.go
  www/src/views/editor.ts
Labels: Enhancement, Frontend

#144 doc+router+tool: add online REST API docs at /doc/restapi
  doc/restapi/Roaster-REST-API.md
  router/route/static.go
  router/router.go
  tool/build-production.sh
Labels: Backend, Enhancement, Frontend

#145 model+router+www: handle resume session correctly & fix status code writing in router
  model/user.go
  router/route/handler.go
  router/route/session.go
  router/route/user.go
  www/src/index.ts
  www/src/services/network.ts
Labels: Backend, Bug, Enhancement, Frontend

#146 test+flake8: 100 % coverage™
  analyze/flake8.go
  analyze/flake8_test.go
Labels: Backend, Enhancement

#147 resize and convert to PNG (fixes: #139)
  analyze/cache/cache_test.go
  analyze/flake8.go
  analyze/flake8_test.go
  go.mod
  go.sum
  model/avatar.go
  model/forwardengineer/schema.go
  model/roast.go
  router/route/avatar.go
  router/route/session.go
  www/src/views/profile.ts
Labels: Backend, Frontend

#148 feed+route+model: feed endpoint
  go.sum
  middleware/cors.go
  middleware/middleware_test.go
  model/feed.go
  model/roast.go
  model/user_test.go
  router/route/feed.go
  router/route/route_test.go
  router/router.go
  util/util_test.go
Labels: In progress

#150 www/src/services/network: fix network service eating server responses
  www/src/services/network.ts
Labels: Bug, Frontend

#152 www: error messages from server displayed on login and register (fixes: #131)
  doc/postgresql/roaster-database-v0.0.2.sql
  model/forwardengineer/schema.go
  router/route/session.go
  router/route/user.go
  www/src/models/apiError.ts
  www/src/views/login.ts
  www/src/views/register.ts
Labels: Backend, DB, Enhancement, Frontend, UI

#160 urgent: better logging to find error on AWS
  router/route/avatar.go
  router/route/roast.go
  router/route/user.go
Labels: ULTRA URGENT, Urgent, WHATEVERCOMESAFTERULTRAURGENT

#159 www: add global and user feed
  model/feed.go
  router/route/feed.go
  www/package-lock.json
  www/package.json
  www/src/index.ts
  www/src/views/about.ts
  www/src/views/feed.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/statistics.ts
  www/src/views/user.ts
Labels: Frontend, UI

#157 database model for friends
  doc/postgresql/roaster-database-v0.0.2.sql
  doc/restapi/Roaster-REST-API.md
  model/forwardengineer/schema.go
  model/roast.go
  model/user.go
  router/route/user.go
  www/src/models/user.ts
  www/src/views/login.ts
  www/src/views/profile.ts
  www/src/views/user.ts
Labels: Backend, DB

#162 www: show global, friends and user statistics
  model/statistics.go
  router/route/statistics.go
  www/.eslintrc.json
  www/package-lock.json
  www/package.json
  www/src/models/statistics.ts
  www/src/views/about.ts
  www/src/views/editor.ts
  www/src/views/feed.ts
  www/src/views/home.ts
  www/src/views/login.ts
  www/src/views/nav.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/statistics.ts
  www/src/views/user.ts
Labels: Backend, Enhancement, Frontend, UI

#173 fixes case sensitive duplicate key error message (fixes: #170)
  router/route/user.go
Labels: Bug, PANIC ATTACK

#175 session+router/route+model+www: add `?friends=true` query parameter and minor bugs
  model/feed.go
  model/statistics.go
  router/route/feed.go
  router/route/session.go
  router/route/statistics.go
  session/session.go
  www/src/models/statistics.ts
  www/src/views/feed.ts
Labels: Backend, Enhancement, Frontend

#177 analyze/flake8: use flake8Result instead of whole model.RoastResult
  analyze/flake8.go
Labels: Backend, Bug
