Repository RoastSoftware/roaster, pull requests merged in 2019-01, with the labels that each got.

#185 router/route/roast+www: handle too large snippet RESTfully and add frontend messages and loading indicator
  router/route/roast.go
  www/src/views/home.ts
Labels: Backend, Enhancement, Frontend, UI

#186 www/src/views/{login,register}: sprinkle some icons
  www/src/views/login.ts
  www/src/views/register.ts
Labels: Bloat, Enhancement, Frontend, UI

#190 model+router+www: add user feed (fixes: #180)
  model/feed.go
  router/route/feed.go
  www/src/views/feed.ts
  www/src/views/profile.ts
  www/src/views/user.ts
Labels: Backend, Frontend

#189 error handling for avatar upload (fixes: #188) (fixes: #178)
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/user.ts
Labels: UI

#191 www/src/services/network: do not set CSRF token if not provided by server
  www/src/services/network.ts
Labels: Bug, Frontend

#192 www/src/views/editor: do not overwrite code if already set (fixed: #179)
  www/src/views/editor.ts
Labels: Enhancement, Frontend

#193 www/src/models/statistics: up interval to 1h and time span to 24h
  www/src/models/statistics.ts
Labels: Frontend

#194 www/src/views/editor: fix annoying indents in example code snippet
  www/src/views/editor.ts
Labels: Bug, Frontend

#196 www/src/models/statistics: show placeholder on empty roast ratio
  www/src/models/statistics.ts
Labels: Bug, Frontend, UI

#199 refactor of friends to followee/follower and visual representation of followees
  doc/postgresql/roaster-database-v0.0.2.sql
  doc/restapi/Roaster-REST-API.md
  model/feed.go
  model/forwardengineer/schema.go
  model/statistics.go
  model/user.go
  router/route/user.go
  www/src/models/statistics.ts
  www/src/models/user.ts
  www/src/views/feed.ts
  www/src/views/login.ts
  www/src/views/profile.ts
  www/src/views/register.ts
  www/src/views/statistics.ts
  www/src/views/user.ts
Labels: Backend, Partially fixed, UI

#204 www: fix user page onupdate and update @types/mithril with one minor
  www/package-lock.json
  www/package.json
  www/src/views/user.ts
Labels: Bug, Frontend

#208 added missing refactored files. (fixes: #183) (fixes: #207)
  router/route/feed.go
  router/route/statistics.go
Labels: Backend

#209 www/src/user: fix followee/follower regression since #206
  doc/postgresql/roaster-database-v0.0.2.sql
  model/forwardengineer/schema.go
  www/src/views/user.ts
Labels: Frontend

#212 doc+router+www: add updated API docs, fix search query 404 bug
  doc/restapi/Roaster-REST-API.md
  router/route/search.go
  www/src/views/nav.ts
Labels: Backend, Bug, Docs, Frontend

#214 www/src/views/nav: remove transparent class for search input
  www/src/views/nav.ts
Labels: Frontend, UI

#216 doc/restapi: fix so parameters are displayed
  doc/restapi/Roaster-REST-API.md
Labels: Bug, Docs

#217 doc: I read through and fixed some minor stuff in README.md (fixes: #57)
  README.md
Labels: Docs, Enhancement

#219 doc+model+router: fix unique email constraint
  doc/postgresql/roaster-database-v0.0.2.sql
  model/forwardengineer/schema.go
  router/route/user.go
Labels: Backend, Bug, DB, Docs

#218 user fullname and email is now editable(fixes: #215)
  doc/postgresql/roaster-database-v0.0.1.png
  doc/postgresql/roaster-database-v0.0.1.uml
  doc/postgresql/roaster-database-v0.0.2.png
  doc/postgresql/roaster-database-v0.0.2.uml
  doc/restapi/Roaster-REST-API.md
  model/user.go
  router/route/user.go
  www/src/models/user.ts
  www/src/views/profile.ts
  www/src/views/user.ts
Labels: Backend, DB, Docs, Frontend

#221 www/src/views/home: display score even if zero
  analyze/flake8_test.go
  www/src/models/statistics.ts
  www/src/views/home.ts
Labels: Bug, Frontend

#222 router+www: fix error handling and fix 404 errors in chrome
  router/route/user.go
  www/src/views/register.ts
  www/webpack.common.ts
Labels: Backend, Environment, Frontend

#228 tool: switch to aglio for rendering REST docs
  tool/build-production.sh
  www/package-lock.json
Labels: Docs, Enhancement

#229 doc: add godoc.org badge
  README.md
Labels: Docs

#230 doc/restapi: document all HTTP status codes
  doc/restapi/Roaster-REST-API.md
  router/route/user.go
Labels: Docs
